node {
    env.GIT_COMMIT = sh( script: 'git rev-parse HEAD', returnStdout: true ).trim()
    docker.build("jacksontong/yii2-basic-app:${env.GIT_COMMIT}")
}
pipeline {
    agent {
        docker {
            image "jacksontong/yii2-basic-app:${env.GIT_COMMIT}"
        }
    }
    stages {
        stage('Build') {
            steps {
                sh './get-composer.sh'
                sh 'php composer.phar update --dev --prefer-dist --no-interaction'
            }
        }
        stage('Test') {
            steps {
                sh 'vendor/bin/codecept run'
            }
        }
    }
}
