
/**
 * This pipeline will run a Docker image build
 */

def label = "docker-${UUID.randomUUID().toString()}"

podTemplate(label: label, yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
    ) {


    node(label) {
        def app

        stage('Clone repository') {
            checkout scm
        }

        def GIT_COMMIT = sh( script: 'git rev-parse HEAD', returnStdout: true ).trim()

        stage('Build image') {
            app = docker.build("jacksontong/yii2-basic-app")
        }

        stage('Test') {
            app.inside {
                sh 'vendor/bin/codecept run'
            }
        }
    }
}