pipeline {
  agent {
    kubernetes {
      label 'mypod'
      yamlFile 'jenkins/Pod.yaml'
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('docker') {
          sh 'docker version'
        }
        container('busybox') {
          sh 'echo BUSYBOX_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}'
          sh '/bin/busybox'
        }
      }
    }
  }
}